  
CREATE TABLE poll_data_election (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  election_name TEXT NOT NULL UNIQUE,
  candidate_id INTEGER REFERENCES candidate_id,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);
