CREATE TABLE poll_data_user (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_first_name TEXT NOT NULL,
  user_last_name TEXT NOT NULL,
  user_phone TEXT,
  user_dob DATE,
  user_email TEXT
);