CREATE TABLE poll_data_election_candidate (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    election_id INTEGER REFERENCES poll_data_election(id) ON DELETE CASCADE NOT NULL,
    candidate_id INTEGER REFERENCES poll_data_candidate(id) ON DELETE CASCADE NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);