CREATE TABLE poll_data_vote (
    vote_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    election_id INTEGER REFERENCES poll_data_election(election_id) ON DELETE CASCADE NOT NULL,
    candidate_id INTEGER REFERENCES poll_data_candidate(candidate_id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER REFERENCES poll_data_user(user_id) ON DELETE CASCADE NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    CONSTRAINT unique_votes UNIQUE (election_id, candidate_id, user_id)
);