CREATE TABLE poll_data_user (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_first_name TEXT NOT NULL,
  user_last_name TEXT NOT NULL,
  user_email TEXT,
  user_dob DATE,
  user_password TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);