-- first remove the foreign key constraint from state
ALTER TABLE IF EXISTS states
  DROP COLUMN state_name;

-- DROP the tables and constraints
DROP TABLE IF EXISTS vote;
DROP TABLE IF EXISTS election;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS candidate;

-- create the election table, it depends on no other
CREATE TABLE elections (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  election_name TEXT NOT NULL,
  candidate_id,
  start_date DATE,
  end_date DATE
);

-- create the state table without the foreign key
CREATE TABLE states (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  state_name TEXT NOT NULL
);

-- create the user table
-- make the foreign keys immediately as the two
-- dependencies exist

CREATE TABLE user (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL,
  phone TEXT,
  dob DATE,
  email TEXT
);


CREATE TABLE user_election (
  user_id INTEGER REFERENCES user(id),
  election_id INTEGER REFERENCES election(id),
  start_date DATE,
  end_date DATE,
  PRIMARY KEY (user_id, election_id)
);